apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-operator
  namespace: argo
spec:
  project: default
  source:
    repoURL: https://operator.min.io/
    chart: operator
    targetRevision: 7.0.1
    helm:
      # Optional values override
      values: |
        operator:
          env:
            - name: MINIO_CONSOLE_TLS_ENABLE
              value: "off"
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true