apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio

resources:
- namespace.yaml
- pvc.yaml

configMapGenerator:
- name: example-properties
  files:
    - example.properties