apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openebs

resources:
- namespace.yaml
- old-pc-hdd-pool.yaml
- old-pc-ssd-pool.yaml
- storage-worker-hdd-pool.yaml
- storage-worker-ssd-pool.yaml

configMapGenerator:
- name: openebs-values
  files:
    - values.yaml