apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo
helmCharts:
- name: argo-cd
  repo: oci://ghcr.io/argoproj/argo-helm
  version: 7.8.26
  releaseName: argocd
  valuesFile: values.yaml

resources:
- namespace.yaml
