apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio
helmCharts:
- name: minio-operator
  repo: https://operator.min.io
  version: 7.0.1
  releaseName: minio-operator
  valuesFile: values.yaml

resources:
- namespace.yaml

configMapGenerator:
- name: argo-env
  envs:
  - .env