apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: prometheus-admin-credentials
    files:
      - prometheus/admin-password
      - prometheus/admin-user
  - name: minio-admin-credentials
    files:
      - minio/admin-password
