apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: secrets

resources:
- namespace.yaml

secretGenerator:
  - name: prometheus-admin-credentials
    files:
      - prometheus/admin-password
      - prometheus/admin-user
